import type { GetServerSideProps, GetServerSidePropsContext, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { render } from 'react-dom'
import styles from '../styles/Home.module.css'
import { Item, GetEventsResults, Welcome } from '../types'
import Footer from './components/footer'

const Home: NextPage<{ events: Item[] }> = ({ events }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {events.map((event) => {
        return (
          <div key={event.id} className="eventList">
            <li key={event.id}>
              <Link href={`/events/${event.id}`}>
                <a>
                  {event.name}
                </a>
              </Link>
              <p>
                {event.description}
              </p>
            </li>
          </div>
        );
      })}
      < Footer/>
    </div>
  )
}

// const showEvents: function(): HTMLLIElement {
//   const evts: boolean = this.events && this.props.events.length > 0 ?
//         this.props.partners.map(p=>
//             <li className = "partners" key={p.id}>
//                 <img src={p.img} alt={p.name}/> {p.name} </li>
//         ) : <span></span>;

//     return (
//             <li>{partners}</li>
//     );
// }

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("https://vef2-20222-v3-synilausn.herokuapp.com/events");
  const { items } : Welcome = await res.json();
  return {
    props: {
      events: items,
    },
  };
}

export default Home
